from agent.state import AgentState
from tools.registry import ToolRegistry

def build_prompt(state: AgentState, registry: ToolRegistry) -> str:
    history = ""
    for i in range(len(state.thoughts)):
        history += f"THOUGHT: {state.thoughts[i]}\n"
        if i < len(state.actions):
            history += f"ACTION: {state.actions[i]}\n"
        if i < len(state.observations):
            history += f"RESULT: {state.observations[i]}\n"
        history += "\n"

    tools_desc = ""
    for name, tool in registry.list_tools().items():
        tools_desc += f"- {name}: {tool.description}\n"

    return f"""You are a research agent. You answer questions by using tools step-by-step.

MANDATORY FORMAT — follow this EXACTLY:

Your response must contain EXACTLY two labeled lines. Each label MUST be followed by a colon character. You must choose ONE of these two formats:

Format A (to take an action):
THOUGHT: <your reasoning here>
ACTION: <JSON object here>

Format B (to give a final answer):
THOUGHT: <your reasoning here>
FINAL: <your final answer here>

STRICT RULES:
1. Every label (THOUGHT, ACTION, FINAL) MUST be immediately followed by a colon (:). Writing "THOUGHT " or "ACTION " or "FINAL " without a colon is WRONG.
2. You must output EXACTLY ONE of ACTION: or FINAL: per response — NEVER both.
3. NEVER output RESULT — that is generated by the system.
4. Output ONLY the two labeled lines. No extra text, no explanations, no results.
5. You MUST STOP immediately after finishing the ACTION or FINAL block.
6. The 'input' field in ACTION MUST be a JSON object (a dictionary), NOT a string.

STOPPING CRITERIA:
- Look at "Previous steps" below. 
- If you see a RESULT that already contains the information needed to answer the question, you MUST use Format B (FINAL) immediately.
- DO NOT repeat the same ACTION if you already have the result in your history.

CORRECT example (Format A):
THOUGHT: I need to search for information about X.
ACTION: {{"tool": "search", "input": {{"query": "X"}}}}

CORRECT example (Format A - CalculatorTool):
THOUGHT: I need to calculate 2 + 2.
ACTION: {{"tool": "calculator", "input": {{"expression": "2+2"}}}}

CORRECT example (Format A - SearchLocalKnowledgeTool):
THOUGHT: I need to search for semiconductor info.
ACTION: {{"tool": "search_local_knowledge", "input": {{"query": "semiconductor"}}}}

CORRECT example (Format B):
THOUGHT: I now have enough information to answer.
FINAL: The answer is Y because of Z.

Available Tools:
{tools_desc}

Question:
{state.question}

CONVERSATION HISTORY (Look here for results!):
{history}

Iteration: {state.iteration}/{state.max_iterations}

If the answer to the question is already present in a RESULT above, YOU MUST USE FINAL NOW.
"""