from agent.state import AgentState

def build_prompt(state: AgentState) -> str:
    history = ""
    
    for i in range(len(state.thoughts)):
        history += f"THOUGHT: {state.thoughts[i]}\n"
        history += f"ACTION: {state.actions[i]}\n"
        history += f"OBSERVATION: {state.observations[i]}\n"

    return f"""
You are a research agent.

CRITICAL RULES:
- You must output EXACTLY ONE of the following:
  (1) THOUGHT + ACTION
  (2) THOUGHT + FINAL
- NEVER output both ACTION and FINAL.
- NEVER output OBSERVATION.
- OBSERVATION is generated by the system, not you.
- Output nothing except the required fields.

Valid formats:

THOUGHT: <reasoning>
ACTION: <next action>

OR

THOUGHT: <reasoning>
FINAL: <final answer>

Question:
{state.question}

Previous steps:
{history}

Iteration: {state.iteration}/{state.max_iterations}
"""